# hw1:企鹅体重分析
1.import
2.pd.read
3.data washing
4.data reshape
5.data analysis

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('penguins.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   species         8 non-null      object
 1   island          8 non-null      object
 2   bill_length_mm  7 non-null      float64
 3   bill_depth_mm   7 non-null      float64
 4   fill_length_mm  7 non-null      float64
 5   body_mass_g     7 non-null      float64
 6   sex             7 non-null      object
dtypes: float64(4), object(3)
memory usage: 580.0+ bytes

In [3]:
# 数据清洗
print(df.isna().sum())
df.dropna(inplace = True)

species           0
island            0
bill_length_mm    1
bill_depth_mm     1
fill_length_mm    1
body_mass_g       1
sex               1
dtype: int64

In [4]:
# 数据特征构造
df.head()
df['sex'] = df['sex'].astype('category')
df['bill_ratio'] = df['bill_length_mm']/df['bill_depth_mm']
df

,species,island,bill_length_mm,bill_depth_mm,fill_length_mm,body_mass_g,sex,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115
3,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554
4,Biscos,Whatever,38.8,18.3,183.0,3670.0,Male,2.120219
5,Biscos,Whatever,34.6,18.5,180.0,3500.0,Female,1.870270
6,Apolis,Notknown,37.8,18.7,182.0,3700.0,Male,2.021390
7,Apolis,Notknown,36.6,18.0,177.0,3440.0,Female,2.033333

In [10]:
# 数据分析
labels = ['低', '中', '高']
df['mass_level'] = pd.cut(df['body_mass_g'],bins = 3,labels = labels)
print(df['mass_level'].value_counts())
# 按岛屿、性别分组分析
df.groupby(['sex','island']).agg(
    {
        'body_mass_g':['mean', 'count']
    }
)

mass_level
低    3
高    3
中    1
Name: count, dtype: int64

C:\Users\dell\AppData\Local\Temp\ipykernel_17648\1184917293.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','island']).agg(

                 body_mass_g
                        mean count
sex    island
Female Notknown       3440.0     1
       Torgersen      3625.0     2
       Whatever       3500.0     1
Male   Notknown       3700.0     1
       Torgersen      3750.0     1
       Whatever       3670.0     1